
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'f1_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'f1_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  catalog: "f1_championship"
  source_schema: "source"
  bronze_schema: "bronze"
  silver_schema: "silver"
  gold_schema: "gold"
  reference_schema: "reference"
  source_volume: "raw_file"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
seeds:
  f1_dbt:
    +schema: reference

models:
  f1_dbt:
    # Config indicated by + and applies to all files under models/<folder_name>/
    bronze:
      +materialized: table
      +schema: bronze
      +docs:
        node_color: "#b76f27"
    silver:
      +materialized: table
      +schema: silver
      +docs:
        node_color: "#767676"
    gold:
      +materalized: table
      +schema: gold
      +docs:
        node_color: "#9f7e33"

snapshots:
  f1_dbt:
    +target_schema: snapshots